### ISSUE TITLE
Error reading current mode : Cannot run glxinfo : Failed to execute 'glxinfo' : Error: unable to open display 

### ISSUE THREAD

**Issue by Artisflowing** [Askannz/optimus-manager#201]
Hello!

Optimus-manager stopped working for me after a system update recently.
The output during tty mode is...

`Error reading current mode : Cannot run glxinfo : Failed to execute 'glxinfo' : Error: unable to open display`

There is more output too it but piping didn't catch it. 
I'll try to update this asap with that info.

**System info**
OS - Arch Linux
Kernel - 4.19.98-1-lts
WM - Openbox
DM- Lightdm
Laptop - Clevo N855HJ 
Version - Optimus Manager (Client) version 1.2.2

**Logs**
[OMboot_setup.txt](https://github.com/Askannz/optimus-manager/files/4116938/OMboot_setup.txt)
[OMgpu_setup.txt](https://github.com/Askannz/optimus-manager/files/4116939/OMgpu_setup.txt)
[OMprime_setup.txt](https://github.com/Askannz/optimus-manager/files/4116940/OMprime_setup.txt)

**Comment by Artisflowing** [comment]
Here's a photo of the extra info that pipe didn't catch.
Will convert into text soon.
![image](https://user-images.githubusercontent.com/7607506/73227883-d880b680-4129-11ea-83fe-0810ba56462a.png)

**Comment by Askannz** [comment]
Yeah that Python crash has been fixed already (https://github.com/Askannz/optimus-manager/commit/b4d07c74c6445d794bf8f8928790826cc29b0230), the fix just hasn't made its way into a release yet.

Use optimus-manager-git for now.

**Comment by Artisflowing** [comment]
Thanks for the info!

**Comment by Artisflowing** [comment]
The...
`Error reading current mode : Cannot run glxinfo : Failed to execute 'glxinfo' : Error: unable to open display`
...is still persisting after changing to optimus-manager-git.

**Comment by Kr1ss-XD** [comment]
I assume you entered that command in a tty session (the screenshot you posted looks like if you did). 

Since `glxinfo` needs an X display, the error would be the supposed behavior if that's the case.
If so, could you pls try again in a terminal emulator inside a graphical session ?

**Comment by enigmatic-system** [comment]
@Kr1ss-XD 
You're correct. 
glxinfo is running correctly now.

I'm confused on where this leaves me though.

**Comment by Kr1ss-XD** [comment]
This seems to be another problem. I'm afraid I can't help you with that, since I'm not experienced with display managers nor with OpenBox, sorry.

**Comment by enigmatic-system** [comment]
Thanks for the info @Kr1ss-XD hopefully @Askannz has a suggestion.
